import type { Locale } from "@/lib/i18n";

export const UI_COPY = {
  en: {
    common: {
      jumpToPage: "Jump to page",
      apply: "Apply",
      export: "Export",
      template: "Template",
      import: "Import",
      reset: "Reset",
      prev: "Prev",
      next: "Next",
      go: "Go",
      showingZero: "Showing 0 results",
      rows: "rows",
      none: "-",
      close: "Close dialog",
      showingRange: (start: number, end: number, total: number) =>
        `Showing ${start}-${end} of ${total} results`,
    },
    nav: {
      appName: "Farm Domain Manager",
      overview: "Overview",
      servers: "Servers",
      domains: "Domains",
      users: "Users",
      language: "Language",
      theme: "Theme",
      light: "Light",
      dark: "Dark",
      system: "System",
      thai: "TH",
      english: "EN",
      roles: {
        admin: "Admin",
        editor: "Editor",
        viewer: "Viewer",
      },
    },
    overview: {
      introLabel: "Operations overview",
      introDescription:
        "Operational summary for tracking domain volume, pending setup work, missing monitoring, and the items that need attention before drilling into detail pages.",
      operationalPosture: "Operational posture",
      operationalPostureDescription:
        "Live operational posture across domains, setup backlog, and monitoring coverage.",
      serviceReadiness: "Service readiness",
      serviceReadinessDescription:
        "Track setup completion across external services.",
      statusMix: "Status mix",
      statusMixDescription: "Snapshot of current domain health states.",
      serverLoad: "Server load",
      serverLoadDescription: "Top servers ranked by attached domains.",
      priorityDescription: "Records that need manual attention before rollout.",
      latestInventoryDescription: "Latest records added to the active inventory.",
      serverSnapshotDescription:
        "Server inventory with profile, provider, region, and domain capacity.",
      issueDomainsCount: "Domains currently marked as issue.",
      coverage: "coverage",
      backlog: "backlog",
      infrastructure: "infrastructure",
      inventory: "inventory",
      totalLabel: "total",
      readySuffix: "ready",
      openDomainBoard: "Open Domain Board",
      priorityQueue: "Priority queue",
      recentDomains: "Recent domains",
      serverSnapshot: "Server snapshot",
      noIssues: "There are no issue domains right now",
      openFullInventory: "Open full inventory",
      metrics: {
        domains: "Total Domains",
        missingMonitoring: "Missing Monitoring",
        pendingSetup: "Pending Setup",
        servers: "Servers",
      },
      domainUnit: "domains",
      serverUnit: "servers",
      snapshotColumns: {
        domains: "Domains",
        profile: "Profile",
        provider: "Provider",
        region: "Region",
        server: "Server",
      },
    },
    domains: {
      introDescription:
        "Primary workspace for searching, filtering, and editing domain records row by row with the table kept as the main surface.",
      workspace: "Domains workspace",
      recordsSuffix: "records",
      missingMonitoringSuffix: "missing monitoring",
      issueStatesSuffix: "issue states",
      serverUnit: "servers",
      searchPlaceholder: "Search domain, IP, server, owner",
      emptyState: "No domains matched the selected filters",
      allServers: "All servers",
      allStatuses: "All statuses",
      allMonitoring: "All monitoring",
      monitoringReady: "Monitoring ready",
      monitoringMissing: "Monitoring missing",
      tableColumns: {
        action: "Action",
        domain: "Domain",
        host: "Host",
        note: "Note",
        panel: "Panel",
        postman: "Postman",
        profile: "Profile",
        s3: "S3",
        server: "Server",
        status: "Status",
        subdomain: "Subdomain",
        uptime: "Uptime",
      },
    },
    servers: {
      introDescription:
        "View the full server inventory in one place with profile, provider, environment, and attached domain counts per machine.",
      linkedDomainsSuffix: "linked domains",
      domainCountSuffix: "domains",
      serverUnit: "servers",
      searchPlaceholder: "Search server, IP, profile, region, note",
      emptyState: "No servers matched the selected filters",
      allProviders: "All providers",
      allEnvironments: "All environments",
      allServers: "All servers",
      openDomains: "Open Domains",
      tableColumns: {
        action: "Action",
        domains: "Domains",
        environment: "Environment",
        note: "Note",
        profile: "Profile",
        provider: "Provider",
        region: "Region",
        server: "Server",
      },
    },
    users: {
      introDescription:
        "Admin-only workspace for managing user access, role assignments, profile scope, and account status.",
      userUnit: "users",
      activeUsers: "active users",
      adminUsers: "admins",
      emptyState: "No users found",
      createUser: "Create user",
      editUser: "Edit user",
      tableColumns: {
        user: "User",
        username: "Username",
        role: "Role",
        profile: "Profile",
        status: "Status",
        updatedAt: "Updated",
        action: "Action",
      },
      statusActive: "Active",
      statusInactive: "Inactive",
    },
    dialogs: {
      addServer: "Add Server",
      addDomain: "Add Domain",
      edit: "Edit",
      createServerTitle: "Create Server",
      createServerDescription:
        "Add a new machine and store only infrastructure information.",
      editServerTitle: "Edit Server",
      editServerDescription: "Update infrastructure details for this machine.",
      createDomainTitle: "Create Domain",
      createDomainDescription:
        "Add a new domain and attach it to the related server.",
      importServersTitle: "Import Servers",
      importServersDescription:
        "Upload a CSV or JSON file to upsert server inventory records.",
      importDomainsTitle: "Import Domains",
      importDomainsDescription:
        "Upload a CSV or JSON file to upsert domain records and map them to existing servers.",
      importServerFlowTitle: "Server target",
      importServerFlowDescription:
        "Choose an existing server for all imported rows or create a new server before import.",
      serverMode: "Server mode",
      useExistingServer: "Use existing server",
      createServerBeforeImport: "Create server before import",
      editDomainTitle: "Edit Domain",
      createUserTitle: "Create User",
      createUserDescription: "Create a new account and assign its role and profile scope.",
      editUserTitle: "Edit User",
      editUserDescription: "Update role, profile scope, account status, or reset the password.",
      deleteServer: "Delete server",
      deleteConfirmationTitle: "Confirm deletion",
      deleteConfirmationDescription:
        "This action is permanent. Review the record once more before removing it from the inventory.",
      deleteConfirmationCancel: "Keep record",
      deleteConfirmationConfirm: "Delete now",
      confirmDeleteServer: "Delete this server permanently?",
      confirmDeleteDomain: "Delete this domain permanently?",
      linkedDomainsBlockDelete: "Remove linked domains before deleting this server",
      chooseImportFile: "Choose CSV or JSON file",
      downloadTemplate: "Download template",
      previewServers: "Server preview",
      previewDomains: "Domain preview",
      previewEmpty: "No preview rows available from this file.",
      dryRunTitle: "Dry-run report",
      runDryRun: "Analyze import",
      dryRunCreate: "Create",
      dryRunUpdate: "Update",
      dryRunSkip: "Skip",
      dryRunRow: "Row",
      dryRunAction: "Action",
      dryRunTarget: "Target",
      dryRunReason: "Reason",
      dryRunErrorPrefix: "Dry run failed",
      reasonDuplicateInFile: "Duplicate in file",
      reasonServerNotFound: "Server not found",
      reasonInvalidData: "Invalid data",
      importWarningsTitle: "Warnings",
      skippedReasonCount: (reason: string, count: number) => `${reason}: ${count} row${count === 1 ? "" : "s"}`,
      importSupportsSheetCsv:
        "Supports CSV from the original sheet format and standard CSV/JSON templates.",
      importSummary: (fileName: string, importedCount: number, skippedCount: number) =>
        `${fileName}: imported ${importedCount} rows${skippedCount > 0 ? `, skipped ${skippedCount}` : ""}.`,
      importProcessedTotal: (totalCount: number) => `${totalCount} total rows processed`,
      importErrorPrefix: "Import failed",
      importServers: "Import servers",
      importDomains: "Import domains",
      selectServer: "Select server",
      serverName: "Server name",
      ipAddress: "IP address",
      profileName: "Profile name",
      region: "Region",
      note: "Note",
      operationalNote: "Operational note",
      domainName: "Domain name",
      previewHostType: "Host type",
      previewStatus: "Status",
      subdomainProvider: "Subdomain provider",
      ownerProfile: "Owner profile",
      userName: "User name",
      username: "Username",
      email: "Email",
      role: "Role",
      password: "Password",
      resetPassword: "Reset password",
      accountStatus: "Account status",
      activeAccount: "Active account",
      createServer: "Create server",
      createDomain: "Create domain",
      createUser: "Create user",
      saveChanges: "Save changes",
      deleteDomain: "Delete domain",
      requiredFieldMessage: "This field is required.",
      invalidIpAddressFieldMessage: "Enter a valid IPv4 address such as 18.142.91.10.",
      invalidDomainNameFieldMessage: "Enter a valid domain name such as example.com.",
      invalidUsernameFieldMessage: "Use 3-32 letters, numbers, dots, dashes, or underscores.",
      serverCreatedToast: "Server created.",
      serverUpdatedToast: "Server updated.",
      serverDeletedToast: "Server deleted.",
      domainCreatedToast: "Domain created.",
      domainUpdatedToast: "Domain updated.",
      domainDeletedToast: "Domain deleted.",
      validationToast: "Complete the required fields before submitting.",
      invalidIpAddressToast: "Enter a valid IPv4 address such as 18.142.91.10.",
      invalidDomainNameToast: "Enter a valid domain name such as example.com.",
      invalidUsernameToast: "Use 3-32 letters, numbers, dots, dashes, or underscores for the username.",
      duplicateServerToast: "A server with the same name or IP already exists.",
      duplicateDomainToast: "This domain already exists in the inventory.",
      duplicateEmailToast: "A user with this email already exists.",
      duplicateUsernameToast: "A user with this username already exists.",
      protectedAdminToast: "You cannot remove or deactivate the last active admin.",
      userCreatedToast: "User created.",
      userUpdatedToast: "User updated.",
      saveFailedToast: "The record could not be saved. Refresh and try again.",
      notFoundToast: "The record could not be found.",
      actionFailedToast: "The action failed. Try again.",
      unauthorizedToast: "You do not have permission to perform this action.",
      readOnlyAccess: "Read-only access",
      limitedAccess: "Limited access",
    },
  },
  th: {
    common: {
      jumpToPage: "ไปหน้าที่",
      apply: "ใช้งานตัวกรอง",
      export: "ส่งออก",
      template: "เทมเพลต",
      import: "นำเข้า",
      reset: "ล้างค่า",
      prev: "ก่อนหน้า",
      next: "ถัดไป",
      go: "ไป",
      showingZero: "แสดงผล 0 รายการ",
      rows: "แถว",
      none: "-",
      close: "ปิดหน้าต่าง",
      showingRange: (start: number, end: number, total: number) =>
        `แสดง ${start}-${end} จาก ${total} รายการ`,
    },
    nav: {
      appName: "Farm Domain Manager",
      overview: "ภาพรวม",
      servers: "เซิร์ฟเวอร์",
      domains: "โดเมน",
      users: "ผู้ใช้",
      language: "ภาษา",
      theme: "ธีม",
      light: "สว่าง",
      dark: "มืด",
      system: "ระบบ",
      thai: "TH",
      english: "EN",
      roles: {
        admin: "ผู้ดูแล",
        editor: "ผู้แก้ไข",
        viewer: "ผู้ดูอย่างเดียว",
      },
    },
    overview: {
      introLabel: "ภาพรวมการปฏิบัติงาน",
      introDescription:
        "ภาพรวมระบบสำหรับดูจำนวนโดเมน งาน setup ที่ยังค้าง จุดที่ยังไม่มี monitoring และรายการที่ควรไล่ตรวจต่อก่อนลงไปหน้าเฉพาะทาง",
      operationalPosture: "สรุปสถานะการปฏิบัติงาน",
      operationalPostureDescription:
        "ภาพรวมสดของจำนวนโดเมน งานค้าง และความพร้อมของ monitoring ในระบบ",
      serviceReadiness: "ความพร้อมของบริการ",
      serviceReadinessDescription:
        "ติดตามความคืบหน้าของการเชื่อมต่อบริการภายนอกแต่ละตัว",
      statusMix: "สัดส่วนสถานะ",
      statusMixDescription: "สรุปภาพรวมสถานะปัจจุบันของโดเมนทั้งหมด",
      serverLoad: "ภาระงานของเซิร์ฟเวอร์",
      serverLoadDescription: "จัดอันดับเครื่องที่มีจำนวนโดเมนผูกอยู่สูงสุด",
      priorityDescription: "รายการที่ยังต้องตรวจหรือแก้ไขก่อนใช้งานต่อ",
      latestInventoryDescription: "รายการล่าสุดที่ถูกเพิ่มเข้ามาใน inventory",
      serverSnapshotDescription:
        "มุมมอง inventory ของเครื่องพร้อม profile, provider, region และจำนวนโดเมน",
      issueDomainsCount: "โดเมนที่ถูกระบุเป็น issue อยู่ในตอนนี้",
      coverage: "coverage",
      backlog: "backlog",
      infrastructure: "infrastructure",
      inventory: "inventory",
      totalLabel: "รวม",
      readySuffix: "พร้อม",
      openDomainBoard: "เปิดหน้าจัดการโดเมน",
      priorityQueue: "คิวงานสำคัญ",
      recentDomains: "โดเมนล่าสุด",
      serverSnapshot: "สรุปเซิร์ฟเวอร์",
      noIssues: "ไม่มีโดเมนที่เป็น issue ตอนนี้",
      openFullInventory: "เปิด inventory เต็ม",
      metrics: {
        domains: "โดเมนทั้งหมด",
        missingMonitoring: "ยังไม่มี monitoring",
        pendingSetup: "งาน setup ค้าง",
        servers: "เซิร์ฟเวอร์",
      },
      domainUnit: "โดเมน",
      serverUnit: "เซิร์ฟเวอร์",
      snapshotColumns: {
        domains: "โดเมน",
        profile: "โปรไฟล์",
        provider: "ผู้ให้บริการ",
        region: "Region",
        server: "เซิร์ฟเวอร์",
      },
    },
    domains: {
      introDescription:
        "มุมมองหลักสำหรับค้นหา กรอง และแก้ไขข้อมูลโดเมนแบบแถวต่อแถวโดยให้ตารางเป็นตัวหลักของหน้า",
      workspace: "พื้นที่จัดการโดเมน",
      recordsSuffix: "รายการ",
      missingMonitoringSuffix: "รายการที่ยังไม่มี monitoring",
      issueStatesSuffix: "รายการสถานะ issue",
      serverUnit: "เซิร์ฟเวอร์",
      searchPlaceholder: "ค้นหาโดเมน, IP, เซิร์ฟเวอร์, owner",
      emptyState: "ไม่พบโดเมนตามเงื่อนไขที่เลือก",
      allServers: "ทุกเซิร์ฟเวอร์",
      allStatuses: "ทุกสถานะ",
      allMonitoring: "ทุกสถานะ monitoring",
      monitoringReady: "Monitoring พร้อม",
      monitoringMissing: "Monitoring ยังไม่พร้อม",
      tableColumns: {
        action: "การจัดการ",
        domain: "โดเมน",
        host: "Host",
        note: "โน้ต",
        panel: "Panel",
        postman: "Postman",
        profile: "โปรไฟล์",
        s3: "S3",
        server: "เซิร์ฟเวอร์",
        status: "สถานะ",
        subdomain: "Subdomain",
        uptime: "Uptime",
      },
    },
    servers: {
      introDescription:
        "ดู inventory ของเครื่องทั้งหมดในมุมมองเดียว พร้อม profile, provider, environment และจำนวนโดเมนที่ผูกอยู่ต่อเครื่อง",
      linkedDomainsSuffix: "โดเมนที่ผูกอยู่",
      domainCountSuffix: "โดเมน",
      serverUnit: "เซิร์ฟเวอร์",
      searchPlaceholder: "ค้นหาเซิร์ฟเวอร์, IP, โปรไฟล์, region, note",
      emptyState: "ไม่พบเซิร์ฟเวอร์ตามเงื่อนไขที่เลือก",
      allProviders: "ทุก provider",
      allEnvironments: "ทุก environment",
      allServers: "ทุกเซิร์ฟเวอร์",
      openDomains: "เปิดหน้าโดเมน",
      tableColumns: {
        action: "การจัดการ",
        domains: "โดเมน",
        environment: "Environment",
        note: "โน้ต",
        profile: "โปรไฟล์",
        provider: "Provider",
        region: "Region",
        server: "เซิร์ฟเวอร์",
      },
    },
    users: {
      introDescription:
        "พื้นที่สำหรับผู้ดูแลระบบในการจัดการสิทธิ์ผู้ใช้ บทบาท โปรไฟล์ที่รับผิดชอบ และสถานะการใช้งานบัญชี",
      userUnit: "ผู้ใช้",
      activeUsers: "บัญชีที่ใช้งานอยู่",
      adminUsers: "ผู้ดูแล",
      emptyState: "ไม่พบผู้ใช้ในระบบ",
      createUser: "สร้างผู้ใช้",
      editUser: "แก้ไขผู้ใช้",
      tableColumns: {
        user: "ผู้ใช้",
        username: "Username",
        role: "บทบาท",
        profile: "โปรไฟล์",
        status: "สถานะ",
        updatedAt: "อัปเดตล่าสุด",
        action: "การจัดการ",
      },
      statusActive: "ใช้งานอยู่",
      statusInactive: "ปิดใช้งาน",
    },
    dialogs: {
      addServer: "เพิ่มเซิร์ฟเวอร์",
      addDomain: "เพิ่มโดเมน",
      edit: "แก้ไข",
      createServerTitle: "สร้างเซิร์ฟเวอร์",
      createServerDescription:
        "เพิ่มเครื่องใหม่โดยเก็บเฉพาะข้อมูลโครงสร้างพื้นฐาน",
      editServerTitle: "แก้ไขเซิร์ฟเวอร์",
      editServerDescription: "อัปเดตรายละเอียดโครงสร้างพื้นฐานของเครื่องนี้",
      createDomainTitle: "สร้างโดเมน",
      createDomainDescription: "เพิ่มโดเมนใหม่และผูกกับเครื่องที่เกี่ยวข้อง",
      importServersTitle: "นำเข้าเซิร์ฟเวอร์",
      importServersDescription:
        "อัปโหลดไฟล์ CSV หรือ JSON เพื่อเพิ่มหรืออัปเดตรายการเซิร์ฟเวอร์",
      importDomainsTitle: "นำเข้าโดเมน",
      importDomainsDescription:
        "อัปโหลดไฟล์ CSV หรือ JSON เพื่อเพิ่มหรืออัปเดตรายการโดเมนและผูกกับเซิร์ฟเวอร์ที่มีอยู่",
      importServerFlowTitle: "ปลายทางเซิร์ฟเวอร์",
      importServerFlowDescription:
        "เลือกเซิร์ฟเวอร์ที่มีอยู่สำหรับทุกแถวในไฟล์ หรือสร้างเซิร์ฟเวอร์ใหม่ก่อนนำเข้า",
      serverMode: "โหมดเซิร์ฟเวอร์",
      useExistingServer: "ใช้เซิร์ฟเวอร์เดิม",
      createServerBeforeImport: "สร้างเซิร์ฟเวอร์ก่อนนำเข้า",
      editDomainTitle: "แก้ไขโดเมน",
      createUserTitle: "สร้างผู้ใช้",
      createUserDescription: "เพิ่มบัญชีใหม่ พร้อมกำหนดบทบาทและโปรไฟล์ที่รับผิดชอบ",
      editUserTitle: "แก้ไขผู้ใช้",
      editUserDescription: "อัปเดตบทบาท โปรไฟล์ สถานะบัญชี หรือรีเซ็ตรหัสผ่าน",
      deleteServer: "ลบเซิร์ฟเวอร์",
      deleteConfirmationTitle: "ยืนยันการลบ",
      deleteConfirmationDescription:
        "การลบนี้ไม่สามารถย้อนกลับได้ ตรวจสอบรายการอีกครั้งก่อนลบออกจาก inventory",
      deleteConfirmationCancel: "เก็บรายการไว้",
      deleteConfirmationConfirm: "ยืนยันการลบ",
      confirmDeleteServer: "ยืนยันการลบเซิร์ฟเวอร์นี้ถาวร?",
      confirmDeleteDomain: "ยืนยันการลบโดเมนนี้ถาวร?",
      linkedDomainsBlockDelete: "ต้องลบโดเมนที่ผูกอยู่ก่อนจึงจะลบเซิร์ฟเวอร์ได้",
      chooseImportFile: "เลือกไฟล์ CSV หรือ JSON",
      downloadTemplate: "ดาวน์โหลดเทมเพลต",
      previewServers: "ตัวอย่างเซิร์ฟเวอร์",
      previewDomains: "ตัวอย่างโดเมน",
      previewEmpty: "ไม่มีแถวตัวอย่างจากไฟล์นี้",
      dryRunTitle: "รายงานจำลองก่อนนำเข้า",
      runDryRun: "วิเคราะห์ก่อนนำเข้า",
      dryRunCreate: "สร้างใหม่",
      dryRunUpdate: "อัปเดต",
      dryRunSkip: "ข้าม",
      dryRunRow: "รายการ",
      dryRunAction: "ผลลัพธ์",
      dryRunTarget: "เป้าหมาย",
      dryRunReason: "สาเหตุ",
      dryRunErrorPrefix: "วิเคราะห์ไม่สำเร็จ",
      reasonDuplicateInFile: "ข้อมูลซ้ำในไฟล์",
      reasonServerNotFound: "ไม่พบเซิร์ฟเวอร์",
      reasonInvalidData: "ข้อมูลไม่ผ่านเงื่อนไข",
      importWarningsTitle: "คำเตือน",
      skippedReasonCount: (reason: string, count: number) => `${reason}: ${count} แถว`,
      importSupportsSheetCsv:
        "รองรับทั้ง CSV จากชีตเดิม และไฟล์ CSV/JSON มาตรฐานของระบบ",
      importSummary: (fileName: string, importedCount: number, skippedCount: number) =>
        `${fileName}: นำเข้า ${importedCount} แถว${skippedCount > 0 ? `, ข้าม ${skippedCount}` : ""}`,
      importProcessedTotal: (totalCount: number) => `ประมวลผลทั้งหมด ${totalCount} แถว`,
      importErrorPrefix: "นำเข้าไม่สำเร็จ",
      importServers: "นำเข้าเซิร์ฟเวอร์",
      importDomains: "นำเข้าโดเมน",
      selectServer: "เลือกเซิร์ฟเวอร์",
      serverName: "ชื่อเซิร์ฟเวอร์",
      ipAddress: "IP address",
      profileName: "ชื่อโปรไฟล์",
      region: "Region",
      note: "โน้ต",
      operationalNote: "โน้ตการดำเนินงาน",
      domainName: "ชื่อโดเมน",
      previewHostType: "ประเภท host",
      previewStatus: "สถานะ",
      subdomainProvider: "ผู้ให้บริการ subdomain",
      ownerProfile: "โปรไฟล์ผู้ดูแล",
      userName: "ชื่อผู้ใช้",
      username: "Username",
      email: "อีเมล",
      role: "บทบาท",
      password: "รหัสผ่าน",
      resetPassword: "รีเซ็ตรหัสผ่าน",
      accountStatus: "สถานะบัญชี",
      activeAccount: "บัญชีที่ใช้งานอยู่",
      createServer: "สร้างเซิร์ฟเวอร์",
      createDomain: "สร้างโดเมน",
      createUser: "สร้างผู้ใช้",
      saveChanges: "บันทึกการเปลี่ยนแปลง",
      deleteDomain: "ลบโดเมน",
      requiredFieldMessage: "กรอกข้อมูลในช่องนี้",
      invalidIpAddressFieldMessage: "กรอก IPv4 address ให้ถูกต้อง เช่น 18.142.91.10",
      invalidDomainNameFieldMessage: "กรอกชื่อโดเมนให้ถูกต้อง เช่น example.com",
      invalidUsernameFieldMessage: "Username ต้องยาว 3-32 ตัว ใช้ได้เฉพาะตัวอักษร ตัวเลข จุด ขีดกลาง หรือขีดล่าง",
      serverCreatedToast: "สร้างเซิร์ฟเวอร์แล้ว",
      serverUpdatedToast: "อัปเดตเซิร์ฟเวอร์แล้ว",
      serverDeletedToast: "ลบเซิร์ฟเวอร์แล้ว",
      domainCreatedToast: "สร้างโดเมนแล้ว",
      domainUpdatedToast: "อัปเดตโดเมนแล้ว",
      domainDeletedToast: "ลบโดเมนแล้ว",
      validationToast: "กรอกข้อมูลที่จำเป็นให้ครบก่อนบันทึก",
      invalidIpAddressToast: "กรอก IPv4 address ให้ถูกต้อง เช่น 18.142.91.10",
      invalidDomainNameToast: "กรอกชื่อโดเมนให้ถูกต้อง เช่น example.com",
      invalidUsernameToast: "กรอก username ให้ถูกต้องโดยใช้ตัวอักษร ตัวเลข จุด ขีดกลาง หรือขีดล่าง",
      duplicateServerToast: "มีเซิร์ฟเวอร์ชื่อหรือ IP นี้อยู่แล้ว",
      duplicateDomainToast: "มีโดเมนนี้อยู่ใน inventory แล้ว",
      duplicateEmailToast: "มีผู้ใช้อีเมลนี้อยู่แล้ว",
      duplicateUsernameToast: "มีผู้ใช้ username นี้อยู่แล้ว",
      protectedAdminToast: "ไม่สามารถลดสิทธิ์หรือปิดใช้งานผู้ดูแลคนสุดท้ายได้",
      userCreatedToast: "สร้างผู้ใช้แล้ว",
      userUpdatedToast: "อัปเดตผู้ใช้แล้ว",
      saveFailedToast: "ไม่สามารถบันทึกรายการได้ ลองรีเฟรชแล้วทำใหม่",
      notFoundToast: "ไม่พบรายการที่ต้องการ",
      actionFailedToast: "ทำรายการไม่สำเร็จ ลองใหม่อีกครั้ง",
      unauthorizedToast: "คุณไม่มีสิทธิ์ดำเนินการนี้",
      readOnlyAccess: "สิทธิ์ดูอย่างเดียว",
      limitedAccess: "สิทธิ์จำกัด",
    },
  },
} as const;

export const COMMON_UI_COPY = {
  en: UI_COPY.en.common,
  th: UI_COPY.th.common,
} as const;

export const DOMAINS_COPY = {
  en: UI_COPY.en.domains,
  th: UI_COPY.th.domains,
} as const;

export const SERVERS_COPY = {
  en: UI_COPY.en.servers,
  th: UI_COPY.th.servers,
} as const;

export const USERS_COPY = {
  en: UI_COPY.en.users,
  th: UI_COPY.th.users,
} as const;

export const OVERVIEW_COPY = {
  en: UI_COPY.en.overview,
  th: UI_COPY.th.overview,
} as const;

export function getCopy(locale: Locale) {
  return UI_COPY[locale];
}
